apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: batchpoc
spec:
  backoffLimit: 0
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
        - image: rodriguesflavio/jobbanco7
          command:
            - /bin/sh
            - -c
            - java -jar app.jar jobId=301
          name: batch
          resources: {}
      restartPolicy: Never

status: {}
  ~